name=Rotary_encoder_lite
version=3.0.0
author=Csermendy Bendeguz
maintainer=Csermendy Bendeguz
sentence=Full quadrature rotary encoder library without NeoPixel functionality. 
paragraph=The full library with NeoPixel ring and bar functionality is available at https://www.github.com/Bendeguz-Cs/Rotary_encoder
category=
url=https://github.com/Bendeguz-Cs/Rotary_encoder_lite
architectures=*
includes=Rotary_encoder_lite.h
